### ISSUE TITLE
Can it support 5 rows of data？

### ISSUE THREAD

**Issue by haohao9102** [commandiron/WheelPickerCompose#16]

**Comment by commandiron** [comment]
Thanks for your request. Actually, row count option could be nice. I will look at as soon as possible.

**Comment by haohao9102** [comment]
> Thanks for your request. Actually, row count option could be nice. I will look at as soon as possible.

**Comment by haohao9102** [comment]
I try to change the number of rows, but there will be a jump when the scroll ends, and I can't find the reason

**Comment by commandiron** [comment]
you are right, I can change to number of rows too but this broke the snap and output logic because i believe this change the first visible index. we must find a way to achieve this.

**Comment by commandiron** [comment]
hey, i added rowCount parameter so now number of rows can be change. [This](https://github.com/commandiron/WheelPickerCompose/releases/tag/1.1.8) release include this feature.

**Comment by haohao9102** [comment]
i  see the changes    size.height / rowCount * ((rowCount - 1 )/ 2)   why this calculation？
