### ISSUE TITLE
Add time range in WheelTimePicker

### ISSUE THREAD

**Issue by BadKiko** [commandiron/WheelPickerCompose#18]

**Comment by commandiron** [comment]
thanks for the feature you suggested, this feature can be useful I think. It can be added next release.

**Comment by commandiron** [comment]
this feature needs to be more cleaner code base because Timeformat and backwards features could be create conflict. I will review next rewrite.

**Comment by BadKiko** [comment]
Ok thanks, I will be waiting for this feature, it would be very useful to me for my project
