### ISSUE TITLE
Add feature to dim rows as we move further away from mid row

### ISSUE THREAD

**Issue by gargVader** [commandiron/WheelPickerCompose#25]
![wheel picker](https://user-images.githubusercontent.com/52619530/214339728-01c0c276-127a-4217-9649-6b63964fb805.jpeg)

**Comment by commandiron** [comment]
As the dim rows move away, their rotation and opacity change. I will review the size as well next release.

**Comment by gargVader** [comment]
Opacity is fixed at [`0.2f`](https://github.com/commandiron/WheelPickerCompose/blob/f61dc263588eab25c9f1a36db8012ec4007b3179/wheel-picker-compose/src/main/java/com/commandiron/wheel_picker_compose/core/WheelPicker.kt#L130) even if rows move further away.
You can replace it by `0.2f / (distanceToIndexSnap / singleViewPortHeight)`

**Comment by commandiron** [comment]
hey, ı try your suggestion instead of fixed 0.2f. I am not sure it feels good because you can mostly see 2 row of them while rotating. I'll think about it or I'm open to new suggestions
