### ISSUE TITLE
Textwheelpicker

### ISSUE THREAD

**Issue by kasiopec** [commandiron/WheelPickerCompose#26]
Is there a chance you can remove internal from TextWheelPicker? I would like to use your lib as it looks neat and is full compose built, however text picker is kinda required for me e.g. For gender selection.

**Comment by commandiron** [comment]
hi @kasiopec TextWheelPicker internal removed in [this](https://github.com/commandiron/WheelPickerCompose/releases/tag/1.1.10) release. You can use now.

**Comment by kasiopec** [comment]
You are the best 👍

**Comment by midenok** [comment]
Please update documentation accordingly. I was wondering if it could pick something else than dates.
