### ISSUE TITLE
wheel state doesn't update after scroll finishes 

### ISSUE THREAD

**Issue by Masoudmjm** [commandiron/WheelPickerCompose#31]
I used WheelTextPicker. but when I scroll numbers , the wheel returns to first item. I mean it doesn't save the state

**Comment by commandiron** [comment]
can u share your snipplet?

**Comment by Masoudmjm** [comment]
yes, of course
`WheelTextPicker(
        texts = (min..max).map { it.toString() },
        rowCount = 3,
        size = DpSize(120.dp, 200.dp),
        selectorProperties = WheelPickerDefaults.selectorProperties(
            enabled = true,
            shape = RoundedCornerShape(100.dp),
            color = Color(0xFFFDFDFD),
            border = BorderStroke(2.dp, Color(0xFF2D5DA7)),
        ),
    ) {
        selectedItem(it)
        Log.i("timePicker", it.toString())
    }`
    pardon me for replying late to your message

**Comment by commandiron** [comment]
you must return it value in onScrollFinished block. 

`
WheelTextPicker(
    texts = (0..10).map { it.toString() },
    rowCount = 3,
    size = DpSize(120.dp, 200.dp),
    selectorProperties = WheelPickerDefaults.selectorProperties(
        enabled = true,
        shape = RoundedCornerShape(100.dp),
        color = Color(0xFFFDFDFD),
        border = BorderStroke(2.dp, Color(0xFF2D5DA7)),
    ),
) {
    selectedItem(ama = it)
    it //<-ADD THIS
}
`
