### ISSUE TITLE
Why infiniteLoopEnabled feature is removed?

### ISSUE THREAD

**Issue by dubiao** [commandiron/WheelPickerCompose#40]
This is a good library that save my life time.

I walked around your code and found that you [removed the infinite loop feature](https://github.com/commandiron/WheelPickerCompose/commit/3dfe027f749b3778c0acc55e07c913dc0b3efbb3) in [version 1.0.4](https://github.com/commandiron/WheelPickerCompose/compare/1.0.3...1.0.4) . 

I thought there must be some reasons made you did this. But I didn't find the reason. Can you explain this, please. Or, if it was some bugs, do you have any plans to add it back to this awesome library?

**Comment by commandiron** [comment]
I removed it because it caused various bugs. I can't focus on the library for now, maybe it can be rewritten cleanly later.
