### ISSUE TITLE
Hide Year if there is only one option

### ISSUE THREAD

**Issue by SamPlusPlus** [commandiron/WheelPickerCompose#6]
I am enjoying the WheelPicker. I would like to request the option to hide the year if there is only 1 option.

My use case is that I would like my users to be able to select a date and time in the up coming week. Unless we are heading into the new year, most of the time, the year is obvious and does not need to be displayed.

**Comment by commandiron** [comment]
Hey sam, thanks for your effort. [this](https://github.com/commandiron/WheelPickerCompose/releases/tag/1.1.3) version fix this issue, so you can hide years if you pass yearsRange null.
